### ISSUE TITLE
honeybits in the same machine with honeypot

### ISSUE THREAD

**Issue by nassimabedi** [0x4D31/honeybits#2]
Is it possible(or useful) to install honeybits in the same machine that honeypots run?

**Comment by Waseem-farooqui** [comment]
Yes it is possible to use honeybits on the same machine on which we are running honeypots, as far as usefulness is concern it don't think its useful because it makes no sense.
There are scenarios then how do you want to deploy them where do you want to deploy it.
The actual value of honeybits or honeytokens lies in their deployment.

**Comment by 0x4D31** [comment]
@nassimabedi Yes, as @Waseem-farooqui said, it doesn't make sense to run it on the honeypot itself, as its main purpose is to lure the attackers toward the honeypots or trigger an alert when someone touches honeyfiles.

**Comment by nassimabedi** [comment]
@Waseem-farooqui @0x4D31 Thanks for reply :slightly_smiling_face:
